# Setup Service Account and Role for Tiller with access only to its own namespace
kind: ServiceAccount
apiVersion: v1
metadata:
  name: tiller
  namespace: default
  labels:
    app: helm
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: default
  labels:
    app: helm
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: default
  labels:
    app: helm
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: default
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
