service:
    type: LoadBalancer

sonarProperties:
    sonar.forceAuthentication: true

plugins:
    install:
        - "https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.1.1/sonarqube-community-branch-plugin-1.1.1.jar"
        - "https://binaries.sonarsource.com/Distribution/sonar-ruby-plugin/sonar-ruby-plugin-1.5.0.315.jar"
persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi